parameters:
  - name: vmImage
    type: string
  - name: dotNetVersion
    type: string
  - name: buildConfiguration
    type: string
  - name: buildPlatform
    type: string
  - name: buildProjects
    type: string
  - name: testProjects
    type: string
  - name: warningThreshold
    type: string
  - name: coverageThreshold
    type: string
  - name: sonarCloudEndpoint
    type: string

  - name: sonarCloudOrganization
    type: string

  - name: sonarCloudProjectKey
    type: string

  - name: sonarCloudProjectName
    type: string
  - name: runUnitTests
    type: boolean
    default: true
  - name: runSonarCloudAnalyze
    type: boolean
    default: true

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - ${{ if eq(parameters.runSonarCloudAnalyze, true) }}:
              - template: ../steps/sonarCloud-prepare-template.yml
                parameters:
                  endpoint: ${{ parameters.sonarCloudEndpoint }}
                  organization: ${{ parameters.sonarCloudOrganization }}
                  projectKey: ${{ parameters.sonarCloudProjectKey }}
                  projectName: ${{ parameters.sonarCloudProjectName }}

          - template: ../steps/build-template.yml
            parameters:
              dotNetVersion: ${{ parameters.dotNetVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              buildPlatform: ${{ parameters.buildPlatform }}
              buildProjects: ${{ parameters.buildProjects }}

          - ${{ if eq(parameters.runUnitTests, true) }}:
              - template: ../steps/test-template.yml
                parameters:
                  buildConfiguration: ${{ parameters.buildConfiguration }}
                  buildPlatform: ${{ parameters.buildPlatform }}
                  testProjects: ${{ parameters.testProjects }}

          - template: ../steps/quality-template.yml
            parameters:
              checkCoverage: ${{ parameters.runUnitTests }}
              warningThreshold: ${{ parameters.warningThreshold }}
              coverageThreshold: ${{ parameters.coverageThreshold }}

          - ${{ if eq(parameters.runSonarCloudAnalyze, true) }}:
              - template: ../steps/sonarCloud-finalize-template.yml
