parameters:
  - name: vmImage
    type: string
  - name: dotNetVersion
    type: string
  - name: buildConfiguration
    type: string
  - name: buildPlatform
    type: string
  - name: buildProjects
    type: string

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - task: VersionDotNetCoreAssemblies@2
            displayName: "Set FileVersion on *.csproj $(Build.BuildNumber)"
            inputs:
              Path: "$(Build.SourcesDirectory)"
              VersionNumber: "$(Build.BuildNumber)"
              Injectversion: False
              VersionRegex: '\d+\.\d+\.\d+\.\d+'
              FilenamePattern: ".csproj"
              AddDefault: true
              OutputVersion: "OutputedVersion"

          - template: ../steps/build-template.yml
            parameters:
              dotNetVersion: ${{ parameters.dotNetVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              buildPlatform: ${{ parameters.buildPlatform }}
              buildProjects: ${{ parameters.buildProjects }}
