name: Nuget 'KRO_PACKAGE_NAME' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/KRO_PACKAGE_NAME/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
KRO_PACKAGES
