name: Nuget 'KRO_PACKAGE_NAME' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

resources:
  repositories:
    - repository: Krosoft.Extensions
      type: github
      name: krosoft-dev/Krosoft.Extensions
      endpoint: krosoft-dev

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/KRO_PACKAGE_NAME/*"

extends:
  template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
KRO_PACKAGES
