services:
  # krosoft-extensions.postgres:
  #   image: "postgres:14.3-alpine"
  #   restart: on-failure
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: "positive_extensions"

  krosoft-extensions.redis:
    image: redis:7.2.3-alpine3.19
    restart: on-failure

  krosoft-extensions.samples.dotnet6.api:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet6.api:${TAG_VERSION}

  # krosoft-extensions.samples.dotnet7.api:
  #   image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet7.api:${TAG_VERSION}

  krosoft-extensions.samples.dotnet8.api:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet8.api:${TAG_VERSION}

  krosoft-extensions.samples.dotnet8.blazorapp:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet8.blazorapp:${TAG_VERSION}
    
  krosoft-extensions.samples.dotnet9.api:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet9.api:${TAG_VERSION}
