services:
  krosoft-extensions.redis:
    image: redis:8.10.1-alpine3.23 
    restart: on-failure

  krosoft-extensions.samples.dotnet10.api:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet10.api:${TAG_VERSION}

  krosoft-extensions.samples.dotnet10.blazorapp:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet10.blazorapp:${TAG_VERSION}
