version: "3.4"

services:

  positive-extensions.postgres:
    volumes:
      - ../:/data
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  positive-extensions.redis:
      ports:
        - "6377:6379"


        
  positive-extensions.samples.api:
    build:
      context: ..
      dockerfile: Positive.Extensions.Samples.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "6001:5000"

        
  positive-extensions.samples.dotnet7.api:
    build:
      context: ..
      dockerfile: Positive.Extensions.Samples.DotNet7.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "6002:5000"