name: Nuget 'Krosoft.Extensions.Zip' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Zip/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
      - "Krosoft.Extensions.Zip"
