name: Nuget 'Krosoft.Extensions.Data.EntityFramework.PostgreSql' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Data.EntityFramework.PostgreSql/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
      - "Krosoft.Extensions.Data.Abstractions"
      - "Krosoft.Extensions.Data.EntityFramework"
      - "Krosoft.Extensions.Data.EntityFramework.PostgreSql"
