name: Nuget 'Krosoft.Extensions.Blocking.Memory' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

resources:
  repositories:
    - repository: Krosoft.Extensions
      type: github
      name: krosoft-dev/Krosoft.Extensions
      endpoint: krosoft-dev

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Blocking.Memory/*"

extends:
  template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
     - "Krosoft.Extensions.Blocking.Abstractions"
     - "Krosoft.Extensions.Blocking.Memory"
     

