name: Nuget 'Krosoft.Extensions.Cqrs' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Cqrs/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     
     - "Krosoft.Extensions.Cqrs"

