name: Nuget 'Krosoft.Extensions.Application.Cache.Distributed.Redis' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Application.Cache.Distributed.Redis/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
      - "Krosoft.Extensions.Application.Cache.Distributed.Redis"
      - "Krosoft.Extensions.Cqrs"
      - "Krosoft.Extensions.Hosting"
