name: Nuget 'Krosoft.Extensions.Testing.Data.EntityFramework' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Testing.Data.EntityFramework/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
     
     - "Krosoft.Extensions.Data.Abstractions"
     - "Krosoft.Extensions.Data.EntityFramework"
     - "Krosoft.Extensions.Testing"
     - "Krosoft.Extensions.Testing.Data.EntityFramework"

