name: Nuget 'Krosoft.Extensions.Pdf' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Pdf/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     
     - "Krosoft.Extensions.Pdf"

