name: Nuget 'Krosoft.Extensions.Identity' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Identity/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
     
     - "Krosoft.Extensions.Identity"
     - "Krosoft.Extensions.Identity.Abstractions"

