name: Nuget 'Krosoft.Extensions.WebApi.Swagger.HealthChecks' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.WebApi.Swagger.HealthChecks/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.Core"
     - "Krosoft.Extensions.WebApi.HealthChecks"
     - "Krosoft.Extensions.WebApi.Swagger"
     - "Krosoft.Extensions.WebApi.Swagger.HealthChecks"

