name: Nuget 'Krosoft.Extensions.WebApi.Blocking' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.WebApi.Blocking/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.Blocking"
     - "Krosoft.Extensions.Blocking.Abstractions"
     
     - "Krosoft.Extensions.Identity"
     - "Krosoft.Extensions.Identity.Abstractions"
     - "Krosoft.Extensions.WebApi"
     - "Krosoft.Extensions.WebApi.Blocking"
     - "Krosoft.Extensions.WebApi.Identity"

