name: Nuget 'Krosoft.Extensions.Blocking' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Blocking/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
      - "Krosoft.Extensions.Blocking"
      - "Krosoft.Extensions.Blocking.Abstractions"

      - "Krosoft.Extensions.Identity.Abstractions"
