name: Nuget 'Krosoft.Extensions.Data.Abstractions' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Data.Abstractions/*"

extends:
    template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
     
     - "Krosoft.Extensions.Data.Abstractions"

