name: Nuget - $(Date:yyyy.MM.dd).$(BuildID)

pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  pipelineFilter: "nuget - Krosoft"

stages:
  - stage: Run
    displayName: Run
    jobs:
      - job: Run
        steps:
          # - bash: az --version
          #   displayName: "Show Azure CLI version"

          - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
            env:
              AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
            displayName: "Login Azure DevOps Extension"

          - bash: |
              az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
            displayName: "Set default Azure DevOps organization and project"

          # - bash: |
          #     az pipelines list --org $(System.CollectionUri) --project $(System.TeamProject)
          #   displayName: "Show pipeline list"

          - bash: |
              pipelines=$(az pipelines list --query "[?starts_with(name,'$(pipelineFilter)')].{Name:name, Id:id}" -o json)

              for pipeline in $(echo "$pipelines" | jq -r '.[] | @base64'); do
                  _jq() {
                      echo ${pipeline} | base64 --decode | jq -r ${1}
                  }

                  pipelineName=$(_jq '.Name')
                  pipelineId=$(_jq '.Id')

                  echo "Run '$pipelineName'."
                  
                  # Déclencher la pipeline
                  az pipelines run --org $(System.CollectionUri) --project $(System.TeamProject) --id $pipelineId
              done

            displayName: Run
