name: Nuget 'Krosoft.Extensions.Cqrs' - $(Date:yyyy.MM.dd).$(Rev:r)

pr: none
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Cqrs/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
      - "Krosoft.Extensions.Core"
      - "Krosoft.Extensions.Cqrs"
