name: Nuget 'Krosoft.Extensions.Identity.Abstractions' - $(Date:yyyy.MM.dd).$(Rev:r)

# pr: none
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Identity.Abstractions/*"

extends:
  template: ./templates/pipelines/nuget-pipeline.yml
  parameters:
    packages:
      - "Krosoft.Extensions.Core"
      - "Krosoft.Extensions.Identity.Abstractions"
