name: Nuget - $(Date:yyyy.MM.dd).$(BuildID)

pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: ./templates/stages/run-template.yml
    parameters:
      pipelines: ["nuget - Krosoft.Extensions.Zip"]
