name: Nuget 'Krosoft.Extensions.Identity' - $(Date:yyyy.MM.dd).$(Rev:r)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Identity/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.Identity"
     - "Krosoft.Extensions.Identity.Abstractions"

