name: Nuget 'Krosoft.Extensions.Core' - $(Date:yyyy.MM.dd).$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Core/*"

extends:
  template: ./templates/nuget.yml
  parameters:
    packages:
      - "Krosoft.Extensions.Core"
