name: Nuget 'Krosoft.Extensions.WebApi.Identity' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.WebApi.Identity/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.WebApi.Identity"
     - "Krosoft.Extensions.Core"

