name: Nuget 'Krosoft.Extensions.Data.EntityFramework.InMemory' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Data.EntityFramework.InMemory/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.Core"
     - "Krosoft.Extensions.Data.Abstractions"
     - "Krosoft.Extensions.Data.EntityFramework"
<<<<<<< HEAD
     - "Krosoft.Extensions.Data.EntityFramework.InMemory"
=======
     - "Krosoft.Extensions.Data.Abstractions"
     - "Krosoft.Extensions.Core"
>>>>>>> main

