name: Nuget 'Krosoft.Extensions.Zip' - $(Date:yyyy.MM.dd).$(Rev:r)

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/Krosoft.Extensions.Zip/*"

extends:
  template: ./templates/pipelines/nuget-template.yml
  parameters:
    packages:
     - "Krosoft.Extensions.Zip"
     - "Krosoft.Extensions.Core"

