parameters:
  - name: vmImage
    type: string
  - name: dotNetVersion
    type: string
  - name: buildConfiguration
    type: string
  - name: buildPlatform
    type: string
  - name: buildProjects
    type: string
  - name: packages
    type: object

stages:
  - stage: Pack
    displayName: Pack
    jobs:
      - job: Pack
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - task: VersionDotNetCoreAssemblies@3
            displayName: "Set FileVersion on *.csproj $(Build.BuildNumber)"
            inputs:
              Path: "$(Build.SourcesDirectory)"
              VersionNumber: "$(Build.BuildNumber)"
              Injectversion: False
              VersionRegex: '\d+\.\d+\.\d+\.\d+'
              FilenamePattern: ".csproj"
              AddDefault: true
              OutputVersion: "OutputedVersion"

          - template: ../steps/build-template.yml
            parameters:
              dotNetVersion: ${{ parameters.dotNetVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              buildPlatform: ${{ parameters.buildPlatform }}
              buildProjects: ${{ parameters.buildProjects }}

          - template: ../steps/pack-template.yml
            parameters:
              packages: ${{ parameters.packages }}

          - task: DotNetCoreCLI@2
            displayName: "Push"
            inputs:
              command: "push"
              packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
              nuGetFeedType: "external"
              publishFeedCredentials: "nuget.org"
