parameters:
  - name: dotNetVersion
    type: string
  - name: buildConfiguration
    type: string
  - name: buildPlatform
    type: string
  - name: buildProjects
    type: string

steps:
  - task: UseDotNet@2
    displayName: "Install SDK ${{ parameters.dotNetVersion }}"
    inputs:
      packageType: "sdk"
      version: ${{ parameters.dotNetVersion }}

  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: "restore"
      projects: ${{ parameters.buildProjects }}
      feedsToUse: "select"
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: "build"
      projects: ${{ parameters.buildProjects }}
      arguments: "--no-restore --configuration ${{ parameters.buildConfiguration }} /p:Platform=${{ parameters.buildPlatform }}"
