parameters:
  - name: packages
    type: object
    default: {}

steps:
  - ${{ each package in parameters.packages }}:
      - task: DotNetCoreCLI@2
        displayName: "Pack ${{ package }}"
        inputs:
          command: "pack"
          packagesToPack: ${{ package }}
          nobuild: true
          versioningScheme: "byBuildNumber"
          arguments: "--no-restore"
