parameters:
  - name: checkCoverage
    type: boolean
    default: true
  - name: warningThreshold
    type: number
    default: 30
  - name: coverageThreshold
    type: number
    default: 5

steps:
  - task: BuildQualityChecks@9
    displayName: "Check build quality"
    continueOnError: true
    inputs:
      showStatistics: true
      checkWarnings: true
      warningFailOption: fixed
      warningThreshold: ${{ parameters.warningThreshold }}
      checkCoverage: ${{ parameters.checkCoverage }}
      coverageFailOption: fixed
      coverageType: lines
      coverageThreshold: ${{ parameters.coverageThreshold }}
