parameters:
  - name: endpoint
    type: string
  - name: organization
    type: string
  - name: projectKey
    type: string
  - name: projectName
    type: string
  - name: version
    type: string
    default: $(Build.BuildNumber)

steps:
  - task: SonarCloudPrepare@2
    displayName: "Prepare SonarCloud"
    inputs:
      SonarCloud: ${{ parameters.endpoint }}
      organization: ${{ parameters.organization }}
      scannerMode: "MSBuild"
      projectKey: ${{ parameters.projectKey }}
      projectName: ${{ parameters.projectName }}
      projectVersion: ${{ parameters.version }}
      extraProperties: |
        sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/coverage.opencover.xml"
        sonar.coverage.exclusions="samples/**"
        sonar.verbose=false
