variables:
  # Agent VM image name
  vmImage: "ubuntu-latest"

  # .net
  dotNetVersion: "7.0.x"
  buildConfiguration: "Release"
  buildPlatform: "AnyCPU"
  buildProjects: "**/*.csproj"
  testProjects: "**/*Tests/*.csproj"
  publishProjects: "**/*Api.csproj"
  warningThreshold: 10
  coverageThreshold: 10
